# Generated by Django 5.1 on 2024-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_work_log_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_log',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
