# Generated by Django 5.1 on 2024-09-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_alter_work_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_log',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
