# Generated by Django 5.1.1 on 2024-09-05 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0005_alter_work_log_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Title',
            new_name='title',
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('time_spent', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_log_Test', to='Todo.task')),
            ],
        ),
        migrations.DeleteModel(
            name='work_log',
        ),
    ]
