# Generated by Django 5.1.1 on 2024-09-05 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0006_rename_title_task_title_worklog_delete_work_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_log_test', to='Todo.task'),
        ),
    ]
